### PR TITLE
Vendor okhttp

### PR DESCRIPTION
**Pull request by yyyogev**

### CODE REVIEW

**Comment by yyyogev** [comment]
@adriancole thanks again for your help, it's much appreciated!
Is there a way we can avoid these kinds of update-related problems in the future?

**Comment by adriancole** [comment]
yes. don't use internal classes or use maven shade to repackage internal classes.

**Comment by adriancole** [comment]
fwiw I take responsibility too as I think you shared this with me and originally didn't notice the internal types. but yeah. we never promise any compatibility whatsoever with internal things.

**Comment by yyyogev** [comment]
I see. we'll be happy to be notified in the future for major changes.
Thanks again.

**Comment by adriancole** [comment]
best way is to stay active and at least watch releases on our repo. there are many people in the ecosystem so that's more effective than relying on my memory. my memory is crap.

If you ever see a minor update, that's feature work and possibly of interest to those extending the server. In some cases we intentionally delay release notes, so feel free to ask on gitter if anything is of interest.

**Pull request merged**
